import Team from "../components/About/Team";
import MainHero from "../components/MainHero";
import GridCard from "../utils/GridCard";


export const metadata = {
    title: "About Us - SPA",
    description: "Generated by create next app",
};

const About = () => {
    return (
        <>
            <MainHero
                mainDescription="SudanDevs began as a spark of an idea among a small group of passionate Sudanese developers. We saw the incredible potential for technology to transform our nation and wanted to create a space for others to learn, collaborate, and innovate. What started as informal meetups and workshops quickly grew into a thriving community, and today, we're proud to be a formal organization driving technological change in Sudan."
                mainTitle="Our Story"
            />

            <GridCard />
            <Team />
        
        </>
    );
};

export default About;
