import Tips from "../components/Posts/Tips";
import MainHero from "../components/MainHero";
import FeatuerArticle from "../components/Posts/FeatuerArticle";
import ProjectUpdates from "../components/Posts/ProjectUpdates";
import Search from "../components/Search";

export const metadata = {
    title: "Blog - SPA",
    description: "Generated by create next app",
};

const Article = () => {
    return (
        <main className=" d-flex flex-1 justify-content-center">
            <div
                className="container-fluid d-flex flex-column"
                style={{ maxWidth: "1200px" }}
            >
                <MainHero
                    mainDescription=" Short technical articles, tips for Sudanese programmers, and
                    updates about our organization's projects."
                    mainTitle=" Latest from Tech Innovators of Sudan"
                    search={<Search />}
                />
                <FeatuerArticle />
                <Tips />
                <ProjectUpdates />
            </div>
        </main>
    );
};

export default Article;
