import Tips from "../components/Posts/Tips";
import Banner from "../components/Banner";
import FeatuerArticle from "../components/Posts/FeatuerArticle";
import ProjectUpdates from "../components/Posts/ProjectUpdates";
import Search from "../components/Search";
import Loader from "../components/Loader";

export const metadata = {
    title: "Blog - SPA",
    description: "Generated by create next app",
};

const Article = () => {
    return (
        <>
            <Loader delay={2000} />
            <main className=" d-flex flex-1 justify-content-center">
                <div
                    className="container-fluid d-flex flex-column"
                    style={{ maxWidth: "1200px" }}
                >
                    <Banner
                        mainDescription=" Short technical articles, tips for Sudanese programmers, and
              updates about our organization's projects."
                        mainTitle=" Latest from Tech Innovators of Sudan"
                        search={<Search />}
                    />
                    <FeatuerArticle />
                    <Tips />
                    <ProjectUpdates />
                </div>
            </main>
        </>
    );
};

export default Article;
