import ContactForm from "../components/Contact/ContactForm";
import DescConatct from "../components/Contact/DescConatct";
import SocialLinks from "../components/Contact/SocialLinks";
import Loader from "../components/Loader";

export const metadata = {
    title: "Contact Us - SPA",
    description: "Generated by create next app",
};

const Contact = () => {
 

    return (
        <>
            <Loader delay={2000} />
            <div className="min-vh-100 bg-gray-700 py-5 rounded-3 p-2 service-card-2">
                <div className="container">
                    <div className="row g-5 align-items-start">
                        {/* Left Column - Contact Info */}
                        <div className="col-lg-6">
                            <DescConatct />
                            <SocialLinks />
                        </div>

                        {/* Right Column - Contact Form */}
                        <div className="col-lg-6">
                            <ContactForm />
                        </div>
                    </div>
                </div>

                {/* Footer */}
                <footer className="text-center py-4 mt-5">
                    <p className="text-gray-400 mb-0">
                        © 2025 Sudanese Association Programming. All rights
                        reserved.
                    </p>
                </footer>
            </div>
        </>
    );
};

export default Contact;
