import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import NavBar from "./components/Navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" data-scroll-behavior="smooth">
            <head></head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen`}
            >
                <NavBar />
                <main
                    className="spacing md:p-2 flex-grow"
                    style={{ position: "relative", marginTop:50}}
                >
                    {children}
                </main>
            </body>
        </html>
    );
}
