import img from "../assets/avatar-1.jpg";
export const providers = [
  {
    id: 1,
    name: "Ahmed Ali",
    service: "Web Development",
    image: img,
    rating: 4.8,
    category: "web",
    bio: "مطور ويب متخصص في React و Next.js مع خبرة 5 سنوات.",
    skills: ["React", "Next.js", "Node.js", "MongoDB"],
    certificates: ["شهادة Google Cloud", "شهادة AWS"],
    projects: [
      { title: "E-commerce Website", image: img },
      { title: "Portfolio Website", image: img },
    ],
    feedback: [
      { user: "Sara", comment: "شغل ممتاز واحترافي!" },
      { user: "Mohamed", comment: "التسليم في الوقت المحدد." },
      { user: "Sara", comment: "شغل ممتاز واحترافي!" },
      { user: "Mohamed", comment: "التسليم في الوقت المحدد." },
    ],
    portfolio: "https://exampole.com",
  },
  {
    id: 2,
    name: "Sara Mohamed",
    service: "UI/UX Design",
    image: img,
    rating: 4.5,
    category: "design",
    bio: "مصممة UI/UX بخبرة في تصميم تطبيقات الموبايل ومواقع الويب.",
    skills: ["Figma", "Adobe XD", "Photoshop"],
    certificates: ["شهادة UX من Coursera"],
    projects: [{ title: "Mobile App Design", image: img }],
    feedback: [
      { user: "Lina", comment: "تصاميم إبداعية وسهلة الاستخدام." },
      { user: "Lina", comment: "تصاميم إبداعية وسهلة الاستخدام." },
      { user: "Lina", comment: "تصاميم إبداعية وسهلة الاستخدام." },
    ],
    portfolio: "https://exampole.com",
  },
  {
    id: 3,
    name: "Mohamed Osman",
    service: "Cyber Security",
    image: img,
    rating: 4.7,
    category: "security",
    bio: "خبير أمن سيبراني مع خبرة في اختبار الاختراق وتأمين الشبكات.",
    skills: ["Penetration Testing", "Firewall", "Linux"],
    certificates: ["CEH", "CompTIA Security+"],
    projects: [{ title: "Network Security Audit", image: img }],
    feedback: [{ user: "Ali", comment: "ساعدنا في حماية بنيتنا التحتية." }],
    portfolio: "https://exampole.com",
  },
  {
    id: 4,
    name: "Mohamed Osman",
    service: "Mobile App",
    image: img,
    rating: 4.7,
    category: "mobile",
    bio: "خبير أمن سيبراني مع خبرة في اختبار الاختراق وتأمين الشبكات.",
    skills: ["Penetration Testing", "Firewall", "Linux"],
    certificates: ["CEH", "CompTIA Security+"],
    projects: [{ title: "Network Security Audit", image: img }],
    feedback: [{ user: "Ali", comment: "ساعدنا في حماية بنيتنا التحتية." }],
    portfolio: "https://exampole.com",
  },
  {
    id: 5,
    name: "Mohamed Osman",
    service: "Mobile App",
    image: img,
    rating: 4.7,
    category: "mobile",
    bio: "خبير أمن سيبراني مع خبرة في اختبار الاختراق وتأمين الشبكات.",
    skills: ["Penetration Testing", "Firewall", "Linux"],
    certificates: ["CEH", "CompTIA Security+"],
    projects: [{ title: "Network Security Audit", image: img }],
    feedback: [{ user: "Ali", comment: "ساعدنا في حماية بنيتنا التحتية." }],
    portfolio: "https://exampole.com",
  },
  {
    id: 6,
    name: "Mohamed Osman",
    service: "Mobile App",
    image: img,
    rating: 4.7,
    category: "mobile",
    bio: "خبير أمن سيبراني مع خبرة في اختبار الاختراق وتأمين الشبكات.",
    skills: ["Penetration Testing", "Firewall", "Linux"],
    certificates: ["CEH", "CompTIA Security+"],
    projects: [{ title: "Network Security Audit", image: img }],
    feedback: [{ user: "Ali", comment: "ساعدنا في حماية بنيتنا التحتية." }],
    portfolio: "https://exampole.com",
  },
];
